package com.cbse.restaurant.domain;

import static com.cbse.restaurant.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class MenuItemAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMenuItemAllPropertiesEquals(MenuItem expected, MenuItem actual) {
        assertMenuItemAutoGeneratedPropertiesEquals(expected, actual);
        assertMenuItemAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMenuItemAllUpdatablePropertiesEquals(MenuItem expected, MenuItem actual) {
        assertMenuItemUpdatableFieldsEquals(expected, actual);
        assertMenuItemUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMenuItemAutoGeneratedPropertiesEquals(MenuItem expected, MenuItem actual) {
        assertThat(expected)
            .as("Verify MenuItem auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMenuItemUpdatableFieldsEquals(MenuItem expected, MenuItem actual) {
        assertThat(expected)
            .as("Verify MenuItem relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getDescription()).as("check description").isEqualTo(actual.getDescription()))
            .satisfies(e -> assertThat(e.getPrice()).as("check price").usingComparator(bigDecimalCompareTo).isEqualTo(actual.getPrice()))
            .satisfies(e -> assertThat(e.getCategory()).as("check category").isEqualTo(actual.getCategory()))
            .satisfies(e -> assertThat(e.getSpicyLevel()).as("check spicyLevel").isEqualTo(actual.getSpicyLevel()))
            .satisfies(e -> assertThat(e.getIsVegetarian()).as("check isVegetarian").isEqualTo(actual.getIsVegetarian()))
            .satisfies(e -> assertThat(e.getIsAvailable()).as("check isAvailable").isEqualTo(actual.getIsAvailable()))
            .satisfies(e -> assertThat(e.getImage()).as("check image").isEqualTo(actual.getImage()))
            .satisfies(e -> assertThat(e.getImageContentType()).as("check image contenty type").isEqualTo(actual.getImageContentType()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMenuItemUpdatableRelationshipsEquals(MenuItem expected, MenuItem actual) {
        // empty method
    }
}
